### ISSUE TITLE
Authentication for Pis post-discovery

### ISSUE THREAD

**Issue by annehstevens** [gabrielkrell/finsta#2]
When a teacher comes to the list of available pis, we want to make sure that the user does not browse and work on other pis in other studios. We need some kind of security for the specific pi in their studio, like a pin or password that they might enter to access their pi, but cannot use to access other pis. What can we put in place for this?

**Comment by gabrielkrell** [comment]
Right now there's only a single login (`pi`/`raspberry`) which is the same across devices and doesn't differentiate between authorized/unauthorized or different access levels like teacher/student.  There are a few places we can put our authorized/unauthorized security:

 - In finsta-coordinator.  People would have to authenticate in some way before being shown the link to their Pi.  Auth could be done with FUSE's existing systems (I don't know anything about these).

    | Pros | Cons |
    | --- | -- |
    | Users see only own Pi's URL; curtails abuse, mistakes. |  Complicated implementation? |

 - In finsta-client-setup.  Once they click on the link to a Pi, they'd be prompted for authentication before viewing Finsta or using the terminal.

    | Pros | Cons |
    | --- | --- |
    | PIN could be on sticker on Pi | Not centrally administered; password resets? |
    | Similar to signing in through terminal. | Exposes Pi address to general Internet; DoS, attacks. |
    | | Confusing: what if you have the wrong Pi? |

This will probably end up being implemented in [finsta-coordinator](https://github.com/gabrielkrell/finsta-coordinator/issues) (does rpis.fusestudio.net) or [finsta-client-setup](https://github.com/gabrielkrell/finsta-client-setup/issues) (sets up Pis), so I'll move it over once we talk more about it.  I think we discussed this in one of the meetings as well, but don't remember if we came to any conclusions.  Definitely something we should keep in mind as we go along.

**Comment by gabrielkrell** [comment]
Seems like this has been covered by the new login system.  I'm marking as "abandoned" and closing because it was done in [finsta-coord](https://github.com/gabrielkrell/finsta-coordinator).
