### ISSUE TITLE
Implement terminal wireframe

### ISSUE THREAD

**Issue by gabrielkrell** [gabrielkrell/finsta#7]
Implement [this wireframe](http://3plnjj.axshare.com/#p=page_1) with a link to the main Finsta feed, an embedded window with the terminal, and some code tips / instructions on the bottom.

**Comment by gabrielkrell** [comment]
@annehstevens, do we want to keep the existing landing page (with terminal/finsta option) or should they start out here and use the Finsta link on the left?  Just because the current landing page isn't in the wireframe.

**Comment by annehstevens** [comment]
@gabrielkrell I was intending this to replace the existing landing page.

**Comment by gabrielkrell** [comment]
Slowly getting there:
![image](https://user-images.githubusercontent.com/11408441/34458446-ec9e9830-ed98-11e7-89e6-0a705c62b7c1.png)

**Comment by gabrielkrell** [comment]
@annehstevens While I'm at it, do you want to do a feed with rows of images like Instagram does?

**Comment by annehstevens** [comment]
Sure!

**Comment by annehstevens** [comment]
Hi Gabe!

Happy New Year! Id love to get some time on the calendar to catch up on the FUSE Insta challenge. What works for you this semester?

Anne

**Comment by gabrielkrell** [comment]
Hey Anne,

Happy New Year! This semester I'm free Mondays and Fridays with scattered
availability in the middle of the week.  Would you like to meet Monday?

 - Gabe

**Comment by annehstevens** [comment]
Monday sounds great! How about 11am?

**Comment by gabrielkrell** [comment]
Sure!

**Comment by gabrielkrell** [comment]
I tweaked the spacing (and behavior on small devices) for the homepage, and added the grid stuff for the feed.  Probably ready for review / the next round of wireframes.  

@annehstevens Next meeting we probably should go over trade-offs between how easy the HTML+CSS are for kids to modify and how nice the site looks.

![7137da23 ngrok io_](https://user-images.githubusercontent.com/11408441/35712421-99188726-0787-11e8-9791-5d870cff7f3d.png)


<img width="987" alt="7137da23 ngrok io_finsta" src="https://user-images.githubusercontent.com/11408441/35712564-33fc9bec-0788-11e8-90d9-41fc992e0ec4.png">

**Comment by annehstevens** [comment]
Hi Gabe!

Thanks for this—sorry for the delayed reply. Would you like to meet this afternoon sometime?

**Comment by gabrielkrell** [comment]
Hey Anne, sorry I missed you.  This issue isn't blocking anything / super urgent since I'll mostly be working on the claim process this week.  I'm free Friday if you want; otherwise we can just slot it into the next meeting that comes up.

**Comment by annehstevens** [comment]
Hey Gabe,

Can we set some time to check in about this this week?

Anne

**Comment by gabrielkrell** [comment]
Note: wireframe updated.  Bootstrap style is OK for now.

**Comment by gabrielkrell** [comment]
Closing; will open up new issues for further changes.
